export const helps = [
  {
    image: 'help0',
    class: 'class-help0',
    id: 0,
    text:
      'FINALMENTE VOCÊ CHEGOU! FOMOS CHAMADOS PARA INVESTIGAR ESTA CASA. PARECE QUE ALGUMAS COISAS ESTÃO PONDO A SEGURANÇA DAS CRIANÇAS EM RISCO.',
    textAfter:
      'OPA! ME CHAMOU? FOMOS CHAMADOS PARA INVESTIGAR ESTA CASA. PARECE QUE ALGUMAS COISAS ESTÃO PONDO A SEGURANÇA DAS CRIANÇAS EM RISCO.'
  },
  {
    image: 'help1',
    class: 'class-help1',
    id: 1,
    text:
      'INVESTIGUE AS DUAS IMAGENS E ENCONTRE TODAS AS DIFERENÇAS ENTRE ELAS. QUANDO ACHAR ALGUMA, CLIQUE EM CIMA NA IMAGEM DA ESQUERDA. SE FOR CORRETO VOCÊ VAI RECEBER UM AVISO.',
    textAfter:
      'INVESTIGUE AS DUAS IMAGENS E ENCONTRE TODAS AS DIFERENÇAS ENTRE ELAS. QUANDO ACHAR ALGUMA, CLIQUE EM CIMA NA IMAGEM DA ESQUERDA. SE FOR CORRETO VOCÊ VAI RECEBER UM AVISO.'
  },
  {
    image: 'help2',
    class: 'class-help2',
    id: 2,
    text:
      'SE QUISER REINICIAR O JOGO, CLIQUE EM OPÇÕES. E SE QUISER QUE EU REPITA O QUE FOI DITO, CLIQUE EM AJUDA QUE FICAREI FELIZ EM VOLTAR PARA TE EXPLICAR. AGORA VAMOS COMEÇAR?',
    textAfter:
      'SE QUISER REINICIAR O JOGO, CLIQUE EM <span class="text-bold">OPÇÕES</span>. E SE QUISER QUE EU REPITA O QUE FOI DITO, CLIQUE EM <span class="text-bold">AJUDA</span> QUE FICAREI FELIZ EM VOLTAR PARA TE EXPLICAR. AGORA VAMOS COMEÇAR?'
  }
]
